apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-blue
  labels:
    app: backend-api
    environment: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-api
      environment: blue
  template:
    metadata:
      labels:
        app: backend-api
        environment: blue
    spec:
      containers:
      - name: backend-api
        image: rpillaiakshay/backend-api:latest
        ports:
        - containerPort: 8080
